package demo;

public class ExceptionDemo {

	public static void main(String[]args){    //here it the main method
		
		void dosomething()
		//in main method we have another method doSomething
		{
			
			
		void doMore()//one more method doMore
		{
			int dividend=50,divisor=0;//showing the division with zero
			int divide=dividend/divisor;
			System.out.println("the output is:"+divide);//now it shows error in line 
		}
	}
	}
}
